/**
 * rest-cpp-data-science
 * data science REST API endpoints, parameters, and responses, including information about preprocessing data, training models, making predictions, and evaluating models.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.3.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Scalar_multiply_input.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Scalar_multiply_input::Scalar_multiply_input()
{
    m_c = 0.0;
    m_cIsSet = false;
    m_MatIsSet = false;
}

Scalar_multiply_input::~Scalar_multiply_input()
{
}

void Scalar_multiply_input::validate()
{
    // TODO: implement validation
}

web::json::value Scalar_multiply_input::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_cIsSet)
    {
        val[utility::conversions::to_string_t(U("c"))] = ModelBase::toJson(m_c);
    }
    if(m_MatIsSet)
    {
        val[utility::conversions::to_string_t(U("mat"))] = ModelBase::toJson(m_Mat);
    }

    return val;
}

bool Scalar_multiply_input::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("c"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("c")));
        if(!fieldValue.is_null())
        {
            double refVal_setC;
            ok &= ModelBase::fromJson(fieldValue, refVal_setC);
            setC(refVal_setC);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("mat"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("mat")));
        if(!fieldValue.is_null())
        {
            std::vector<std::vector<double>> refVal_setMat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMat);
            setMat(refVal_setMat);
        }
    }
    return ok;
}

void Scalar_multiply_input::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_cIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("c")), m_c));
    }
    if(m_MatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("mat")), m_Mat));
    }
}

bool Scalar_multiply_input::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("c"))))
    {
        double refVal_setC;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("c"))), refVal_setC );
        setC(refVal_setC);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("mat"))))
    {
        std::vector<std::vector<double>> refVal_setMat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("mat"))), refVal_setMat );
        setMat(refVal_setMat);
    }
    return ok;
}

double Scalar_multiply_input::getC() const
{
    return m_c;
}

void Scalar_multiply_input::setC(double value)
{
    m_c = value;
    m_cIsSet = true;
}

bool Scalar_multiply_input::CIsSet() const
{
    return m_cIsSet;
}

void Scalar_multiply_input::unsetc()
{
    m_cIsSet = false;
}
std::vector<std::vector<double>>& Scalar_multiply_input::getMat()
{
    return m_Mat;
}

void Scalar_multiply_input::setMat(const std::vector<std::vector<double>>& value)
{
    m_Mat = value;
    m_MatIsSet = true;
}

bool Scalar_multiply_input::matIsSet() const
{
    return m_MatIsSet;
}

void Scalar_multiply_input::unsetMat()
{
    m_MatIsSet = false;
}
}
}
}
}


