/**
 * Minimal Pistache
 * This is a sample server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "EchoApiImpl.h"

namespace org::openapitools::server::api
{

    EchoApiImpl::EchoApiImpl(const std::shared_ptr<Pistache::Rest::Router> &rtr)
        : EchoApi(rtr)
    {
    }

    void EchoApiImpl::echo(const std::string &body, Pistache::Http::ResponseWriter &response)
    {
        nlohmann::json json_to_dump;
        std::string string_to_send;
        std::string result = body;
        nlohmann::to_json(json_to_dump, result);
        string_to_send = json_to_dump.dump();
        response.send(Pistache::Http::Code::Ok, string_to_send);
    }

}
