/**
 * Minimal Pistache
 * This is a sample server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "StrengthApiImpl.h"
#include "dspack.h"

namespace org::openapitools::server::api
{

    using namespace org::openapitools::server::model;

    StrengthApiImpl::StrengthApiImpl(const std::shared_ptr<Pistache::Rest::Router> &rtr)
        : StrengthApi(rtr)
    {
    }

    void StrengthApiImpl::strengthen(const Strength_input &strengthInput, Pistache::Http::ResponseWriter &response)
    {
        double expected;
        double actual;
        double result;
        double eps = 0.01;
        nlohmann::json json_to_dump;
        std::string string_to_send;
        actual = strengthInput.getActual();
        expected = strengthInput.getExpected();
        result = strength(actual, expected);
        nlohmann::to_json(json_to_dump, result);
        string_to_send = json_to_dump.dump();
        response.send(Pistache::Http::Code::Ok, string_to_send);
    }

}
