# coding: utf-8

"""
    rest-cpp-data-science

    data science REST API endpoints, parameters, and responses, including information about preprocessing data, training models, making predictions, and evaluating models.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client_py
from openapi_client_py.model.vector_sum_output import VectorSumOutput
from openapi_client_py import configuration


class TestVectorSumOutput(unittest.TestCase):
    """VectorSumOutput unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
