# coding: utf-8

"""
    rest-cpp-data-science

    data science REST API endpoints, parameters, and responses, including information about preprocessing data, training models, making predictions, and evaluating models.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client_py import schemas  # noqa: F401


class BucketizeInput(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            point = schemas.NumberSchema
            bucket_size = schemas.NumberSchema
            __annotations__ = {
                "point": point,
                "bucket_size": bucket_size,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["point"]) -> MetaOapg.properties.point: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bucket_size"]) -> MetaOapg.properties.bucket_size: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["point", "bucket_size", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["point"]) -> typing.Union[MetaOapg.properties.point, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bucket_size"]) -> typing.Union[MetaOapg.properties.bucket_size, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["point", "bucket_size", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        point: typing.Union[MetaOapg.properties.point, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        bucket_size: typing.Union[MetaOapg.properties.bucket_size, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BucketizeInput':
        return super().__new__(
            cls,
            *_args,
            point=point,
            bucket_size=bucket_size,
            _configuration=_configuration,
            **kwargs,
        )
