# coding: utf-8

"""
    rest-cpp-data-science

    data science REST API endpoints, parameters, and responses, including information about preprocessing data, training models, making predictions, and evaluating models.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client_pyng
from openapi_client_pyng.api.gradient_descent_api import GradientDescentApi  # noqa: E501
from openapi_client_pyng.rest import ApiException


class TestGradientDescentApi(unittest.TestCase):
    """GradientDescentApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client_pyng.api.gradient_descent_api.GradientDescentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_difference_quotient_post(self):
        """Test case for difference_quotient_post

        """
        pass

    def test_estimate_gradient_post(self):
        """Test case for estimate_gradient_post

        """
        pass

    def test_in_random_order_post(self):
        """Test case for in_random_order_post

        """
        pass

    def test_maximize_batch_post(self):
        """Test case for maximize_batch_post

        """
        pass

    def test_maximize_stochastic_post(self):
        """Test case for maximize_stochastic_post

        """
        pass

    def test_minimize_batch_post(self):
        """Test case for minimize_batch_post

        """
        pass

    def test_minimize_stochastic_post(self):
        """Test case for minimize_stochastic_post

        """
        pass

    def test_partial_difference_quotient_post(self):
        """Test case for partial_difference_quotient_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
