# coding: utf-8

"""
    rest-cpp-data-science

    data science REST API endpoints, parameters, and responses, including information about preprocessing data, training models, making predictions, and evaluating models.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client_py.paths.accracy.post import AccracyPost
from openapi_client_py.paths.f1_score.post import F1ScorePost
from openapi_client_py.paths.precision.post import PrecisionPost
from openapi_client_py.paths.split_data.post import SplitDataPost
from openapi_client_py.paths.train_test_split.post import TrainTestSplitPost


class MachineLearningApi(
    AccracyPost,
    F1ScorePost,
    PrecisionPost,
    SplitDataPost,
    TrainTestSplitPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
