# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from openapi_client_py.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    SQRT = "/sqrt"
    STRENGTH = "/strength"
    ACCRACY = "/acc&#x60;racy"
    BUCKETIZE = "/bucketize"
    CORRELATION = "/correlation"
    CORRELATION_MATRIX = "/correlation_matrix"
    COVARIANCE = "/covariance"
    DATA_RANGE = "/data_range"
    DE_MEAN = "/de_mean"
    DIFFERENCE_QUOTIENT = "/difference_quotient"
    DISTANCE = "/distance"
    DOT = "/dot"
    ECHO = "/echo"
    ESTIMATE_GRADIENT = "/estimate_gradient"
    F1_SCORE = "/f1_score"
    GET_COLUMN = "/get_column"
    GET_ROW = "/get_row"
    IN_RANDOM_ORDER = "/in_random_order"
    INTERQUARTILE_RANGE = "/interquartile_range"
    MAGNITUDE = "/magnitude"
    MATRIX_ADD = "/matrix_add"
    MAXIMIZE_BATCH = "/maximize_batch"
    MAXIMIZE_STOCHASTIC = "/maximize_stochastic"
    MEAN = "/mean"
    MEDIAN = "/median"
    MINIMIZE_BATCH = "/minimize_batch"
    MINIMIZE_STOCHASTIC = "/minimize_stochastic"
    MODE = "/mode"
    PARTIAL_DIFFERENCE_QUOTIENT = "/partial_difference_quotient"
    PRECISION = "/precision"
    QUANTILE = "/quantile"
    RECALL = "/recall"
    SCALAR_MULTIPLY = "/scalar_multiply"
    SHAPE = "/shape"
    SPLIT_DATA = "/split_data"
    SQUARED_DISTANCE = "/squared_distance"
    STANDARD_DEVIATION = "/standard_deviation"
    SUM_OF_SQUARES = "/sum_of_squares"
    TRAIN_TEST_SPLIT = "/train_test_split"
    VARIANCE = "/variance"
    VECTOR_ADD = "/vector_add"
    VECTOR_MEAN = "/vector_mean"
    VECTOR_SUBTRACT = "/vector_subtract"
    VECTOR_SUM = "/vector_sum"
