/**
 * rest-cpp-data-science
 * data science REST API endpoints, parameters, and responses, including information about preprocessing data, training models, making predictions, and evaluating models.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.3.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MachineLearningApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_MachineLearningApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_MachineLearningApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/Accuracy_input.h"
#include "CppRestOpenAPIClient/model/F1_score_input.h"
#include "CppRestOpenAPIClient/model/Precision_input.h"
#include "CppRestOpenAPIClient/model/Split_data_input.h"
#include "CppRestOpenAPIClient/model/Split_data_output.h"
#include "CppRestOpenAPIClient/model/Train_test_split_input.h"
#include "CppRestOpenAPIClient/model/Train_test_split_output.h"
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  MachineLearningApi 
{
public:

    explicit MachineLearningApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~MachineLearningApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Description of the endpoint
    /// </remarks>
    /// <param name="accuracyInput"> (optional)</param>
    pplx::task<double> accracyPost(
        boost::optional<std::shared_ptr<Accuracy_input>> accuracyInput
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Description of the endpoint
    /// </remarks>
    /// <param name="f1ScoreInput"> (optional)</param>
    pplx::task<double> f1ScorePost(
        boost::optional<std::shared_ptr<F1_score_input>> f1ScoreInput
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Description of the endpoint
    /// </remarks>
    /// <param name="precisionInput"> (optional)</param>
    pplx::task<double> precisionPost(
        boost::optional<std::shared_ptr<Precision_input>> precisionInput
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Description of the endpoint
    /// </remarks>
    /// <param name="splitDataInput"> (optional)</param>
    pplx::task<std::shared_ptr<Split_data_output>> splitDataPost(
        boost::optional<std::shared_ptr<Split_data_input>> splitDataInput
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Description of the endpoint
    /// </remarks>
    /// <param name="trainTestSplitInput"> (optional)</param>
    pplx::task<std::shared_ptr<Train_test_split_output>> trainTestSplitPost(
        boost::optional<std::shared_ptr<Train_test_split_input>> trainTestSplitInput
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_MachineLearningApi_H_ */

